'use strict';

/** Convierte filas [pregunta, opciones, índiceCorrecto, explicación, pista] al formato del juego. */
function pack(rows) {
  return rows.map(([p, o, c, e, h]) => {
    const q = { p, o, c, e };
    if (h) q.h = h;
    return q;
  });
}

/**
 * Cultura general + Geografía (todas las dificultades mezcladas en el mismo pool por nivel).
 * El juego elige al azar 4 fáciles, 3 medias y 3 difíciles y luego baraja el orden de las 10 rondas.
 */
const qPool = {
  facil: pack([
    ['¿Cuál es el animal terrestre más rápido del mundo?', ['León', 'Guepardo', 'Tigre', 'Antílope'], 1, 'El guepardo puede alcanzar velocidades de hasta 110 km/h en carreras cortas.', 'No es el más grande ni el más fuerte, pero en velocidad punta ningún animal terrestre se le acerca.'],
    ['¿Quién pintó la obra conocida como \'La Mona Lisa\'?', ['Pablo Picasso', 'Vincent van Gogh', 'Leonardo da Vinci', 'Miguel Ángel'], 2, 'La Mona Lisa fue pintada por Leonardo da Vinci en el siglo XVI. Es una de las obras más famosas del mundo y se exhibe en el Museo del Louvre en París.', 'El autor también era escultor, ingeniero e inventor, todo a la vez.'],
    ['¿Cómo se llama el ratón famoso de Disney?', ['Donald', 'Goofy', 'Mickey', 'Pluto'], 2, 'Mickey Mouse es el ratón más icónico de Disney, creado en 1928 por Walt Disney y Ub Iwerks. Curiosamente, su primer nombre fue Mortimer, pero la esposa de Walt lo cambió a Mickey. Actualmente es considerado uno de los personajes más reconocidos del mundo.', 'Es el personaje que prácticamente representa a toda la compañía.'],
    ['¿Cuál de estos inventos apareció primero?', ['Teléfono', 'Internet', 'Televisión', 'Ordenador'], 0, 'El teléfono fue inventado en el siglo XIX por Alexander Graham Bell. Los otros inventos llegaron mucho después, especialmente internet, que es del siglo XX.', 'Piensa en el invento que ya existía mucho antes de la era digital.'],
    ['¿Qué planeta es conocido como el \'Planeta Rojo\'?', ['Mercurio', 'Marte', 'Júpiter', 'Venus'], 1, 'Marte recibe este apodo por el óxido de hierro presente en su superficie, que le da un tono rojizo.', 'El óxido de hierro en su superficie le da un tono inconfundible.'],
    ['¿Qué gas necesitan las plantas para hacer la fotosíntesis?', ['Helio', 'Nitrógeno', 'Oxígeno', 'Dióxido de carbono'], 3, 'Las plantas absorben dióxido de carbono y liberan oxígeno durante la fotosíntesis.', 'Es el gas que nosotros expulsamos al respirar.'],
    ['¿Qué animal es conocido como el \'rey de la selva\'?', ['León', 'Tigre', 'Elefante', 'Pantera'], 0, 'La respuesta correcta es \'El león\'. Es un título simbólico por su fuerza y presencia, aparte que los leones no viven en selvas sino en sabanas, pero es un apodo cultural.', 'Es el animal que suele aparecer en escudos y símbolos de poder.'],
    ['¿Cuál es el animal terrestre más grande del mundo?', ['Cachalote', 'Ballena azul', 'Rinoceronte blanco', 'Elefante africano'], 3, 'La ballena azul es el animal más grande del planeta, pero no es terrestre. El animal terrestre más grande es el elefante africano.', 'Es un gigante que vive en tierra firme.'],
    ['¿Cuál es la capital de Islandia?', ['Reikiavik', 'Oslo', 'Helsinki', 'Copenhague'], 0, 'Reikiavik es la capital de Islandia, conocida por su belleza natural y su cultura vibrante.', 'Es la capital que suena tan fría como el país al que pertenece.'],
    ['¿Cuál es la capital de Brasil?', ['Río de Janeiro', 'São Paulo', 'Brasilia', 'Salvador'], 2, 'Brasilia es la capital de Brasil desde 1960. Fue construida específicamente para ser la capital y ayudar a desarrollar el interior del país, reemplazando a Río de Janeiro.', 'La capital no es la ciudad más turística, sino la más planificada.'],
    ['¿Qué país tiene forma de bota?', ['Grecia', 'Italia', 'Chile', 'Portugal'], 1, 'Italia es famosa por su forma geográfica en el mapa, que recuerda a una bota pateando la isla de Sicilia.', 'En el mapa parece que está dando una patada a una isla.'],
    ['¿Qué continente es el más grande del mundo?', ['Asia', 'África', 'Europa', 'América'], 0, 'Asia es el continente más grande tanto en superficie como en población, y alberga países como China e India.', 'Es el continente donde viven las dos naciones más pobladas.'],
    ['¿En qué país se encuentra la Gran Muralla?', ['Japón', 'China', 'Corea del Sur', 'India'], 1, 'La Gran Muralla China es una de las construcciones más famosas del mundo y se extiende por miles de kilómetros.', 'Es una de las estructuras más largas jamás construidas.'],
    ['¿Qué océano está entre América y Europa?', ['Índico', 'Pacífico', 'Atlántico', 'Ártico'], 2, 'El océano Atlántico separa América de Europa y África, siendo el segundo más grande del mundo.', 'Es el océano que cruzaban los barcos rumbo al \'nuevo mundo\'.'],
    ['¿En qué continente se encuentra Egipto?', ['Asia', 'Europa', 'África', 'Oceanía'], 2, 'Egipto está ubicado en el noreste de África, aunque la península del Sinaí conecta con Asia.', 'Es el mismo continente donde se encuentra el desierto del Sahara.'],
    ['¿Cuál es la capital de Turquía?', ['Estambul', 'Ankara', 'Esmirna', 'Bursa'], 1, 'Aunque muchos piensan en Estambul, la capital oficial de Turquía es Ankara desde 1923.', 'No es la ciudad más famosa del país, pero sí la capital.'],
  ]),
  media: pack([
    ['Si tiras dos dados a la vez ¿Qué suma es la más probable?', ['7', '8', '9', '12'], 0, 'La suma 7 es la más probable porque se puede obtener de 6 formas distintas (1+6, 2+5, 3+4, 4+3, 5+2, 6+1), más que cualquier otra suma posible al lanzar dos dados.', 'Es el punto medio exacto entre el mínimo y el máximo que pueden sumar dos dados.'],
    ['¿Cuál de los siguientes números romanos es el mayor?', ['XLIX', 'LXV', 'LXXX', 'XC'], 3, 'XLIX = 49, LXV = 65, LXXX = 80 y XC = 90. Por lo tanto, XC es el número más grande.', 'Busca la combinación que más se acerca a cien.'],
    ['¿Cuál de estos animales no pone huevos?', ['Ornitorrinco', 'Equidna', 'Murciélago', 'Tortuga'], 2, 'El murciélago es un mamífero y, como la mayoría de ellos, da a luz crías vivas. El ornitorrinco y la equidna son excepciones curiosas, ya que son mamíferos que sí ponen huevos.', 'Es el único de la lista que vuela.'],
    ['¿De qué color es una caja negra de un avión?', ['Naranja', 'Gris', 'Azul', 'Negra'], 0, 'Las cajas negras en realidad son de color naranja brillante para facilitar su localización tras un accidente. El nombre viene de su función, no de su color.', 'Se llama de una forma pero se pinta de otra muy diferente, por razones prácticas.'],
    ['¿Qué científico desarrolló la teoría de la relatividad?', ['Albert Einstein', 'Isaac Newton', 'Nikola Tesla', 'Stephen Hawking'], 0, 'Albert Einstein formuló la teoría de la relatividad especial en 1905 y la general en 1915.', 'Su apellido es sinónimo de genio.'],
    ['¿Qué civilización construyó la ciudad de Machu Picchu?', ['Azteca', 'Maya', 'Inca', 'Olmeca'], 2, 'Machu Picchu fue construida por el Imperio Inca en el siglo XV y dada a conocer internacionalmente en 1911.', 'Es la misma civilización que dominó los Andes.'],
    ['¿Cuántos meses tienen exactamente 30 días?', ['3', '4', '2', '5'], 1, 'Los meses que tienen 30 días son abril, junio, septiembre y noviembre, en total 4.', 'Son los meses que no llegan a 31 ni bajan a 28.'],
    ['¿Qué ciudad tiene el metro más antiguo del mundo?', ['París', 'Nueva York', 'Londres', 'Berlín'], 2, 'El metro de Londres abrió en 1863, siendo el primero del mundo. París abrió en 1900, Berlín en 1902 y Nueva York en 1904.', 'Su metro se conoce como \'The Tube\'.'],
    ['¿Qué país es conocido como \'la tierra del sol naciente\'?', ['China', 'Japón', 'Corea del Sur', 'Tailandia'], 1, 'Japón es conocido como \'la tierra del sol naciente\' porque su nombre en japonés (Nihon o Nippon) significa literalmente \'origen del sol\'. Esto se debe a su ubicación al este de China, desde donde se ve salir el sol.', 'El nombre del país ya apunta hacia el amanecer.'],
    ['¿De qué país forma parte Groenlandia?', ['Dinamarca', 'Noruega', 'Suecia', 'Finlandia'], 0, 'Groenlandia es una región autónoma dentro del Reino de Dinamarca. Aunque tiene su propio gobierno, sigue siendo parte de Dinamarca en términos de relaciones internacionales y defensa.', 'Pertenece a un país europeo más pequeño que la isla.'],
    ['¿Qué país tiene la mayor población del mundo actualmente?', ['China', 'Estados Unidos', 'India', 'Indonesia'], 2, 'India superó a China recientemente como el país más poblado del mundo, con más de 1.400 millones de habitantes.', 'Es el país donde viven más de mil millones de personas y sigue creciendo rápido.'],
    ['¿Cuál es la capital de Australia?', ['Sídney', 'Melbourne', 'Canberra', 'Perth'], 2, 'Mucha gente piensa que es Sídney o Melbourne, pero la capital es Canberra. Se eligió como punto intermedio entre ambas ciudades para evitar rivalidades.', 'No es la ciudad más famosa, sino la más neutral.'],
    ['¿Cuál es el país más pequeño del mundo?', ['Mónaco', 'San Marino', 'Liechtenstein', 'Vaticano'], 3, 'El Vaticano es el país más pequeño del mundo, tanto en superficie como en población, y está dentro de la ciudad de Roma.', 'Es tan pequeño que está dentro de otra ciudad.'],
    ['¿Cuál de estas NO forma parte de las 7 maravillas del mundo moderno?', ['Petra', 'La Alhambra', 'Cristo Redentor', 'Chichén Itzá'], 1, 'Las 7 maravillas del mundo moderno son: Petra, Chichén Itzá, Cristo Redentor, Coliseo romano, Gran Muralla China, Machu Picchu y el Taj Mahal. La Alhambra, aunque muy famosa, no forma parte de esta lista.', 'Es un monumento europeo muy visitado que se quedó fuera de la votación final.'],
    ['¿En qué país se encuentra el monte Everest?', ['India', 'Bután', 'China', 'Nepal'], 3, 'El monte Everest se encuentra en la frontera entre Nepal y China, pero la mayoría de su ascenso se realiza desde el lado nepalí.', 'Es el país desde donde parten la mayoría de expediciones.'],
    ['¿Cuál es la capital de Canadá?', ['Toronto', 'Vancouver', 'Ottawa', 'Montreal'], 2, 'Ottawa es la capital de Canadá, aunque Toronto sea la ciudad más grande.', 'No es la ciudad más famosa del país, pero sí la capital.'],
  ]),
  dificil: pack([
    ['¿Cuál es el planeta del sistema solar con más satélites naturales?', ['Júpiter', 'Saturno', 'Urano', 'Neptuno'], 1, 'Saturno es actualmente el planeta con más lunas conocidas. Algunas de ellas, como Titán, son tan grandes que tienen atmósfera propia, algo muy poco común en satélites.\nSaturno: 274-285\nJúpiter: 95-115\nUrano: 28-29\nNeptuno: 16', 'El planeta con anillos también tiene compañía.'],
    ['¿Cuál es el metal más valioso del mundo por peso?', ['Oro', 'Platino', 'Rodio', 'Paladio'], 2, 'El rodio es el metal más valioso por peso debido a su rareza y sus aplicaciones en la industria automotriz para reducir emisiones. Su precio puede superar los 10.000 dólares por onza. El ranking actual por €/g es este:\n1. Rodio: 300-500 €/g\n2. Paladio: 40-80 €/g\n3. Platino 30-40 €/g\n4. Oro: 60-70 €/g', 'El más caro no es el más famoso.'],
    ['¿Cuál de estos planetas del sistema solar es el más frío?', ['Neptuno', 'Urano', 'Saturno', 'Marte'], 1, 'Urano es el planeta más frío del sistema solar, con temperaturas que pueden bajar hasta unos -224 °C. Aunque Neptuno está más lejos del Sol, Urano emite muy poco calor interno, lo que lo hace más frío.', 'La distancia al Sol no es el único factor que decide lo frío que puede ser un planeta.'],
    ['¿Qué país tiene más pirámides en su territorio?', ['Egipto', 'México', 'Sudán', 'Perú'], 2, 'Aunque Egipto es el más famoso, Sudán tiene más pirámides debido a la antigua civilización de Nubia. Así actualmente sería:\nSudan: +200\nEgipto: 118 - 135\nMéxico: 20\nPerú: 26', 'No es el país más famoso por ellas, pero sí el que más tiene.'],
    ['¿Cuál es el órgano más grande del cuerpo humano?', ['Hígado', 'Piel', 'Pulmones', 'Intestino'], 1, 'La piel es el órgano más grande del cuerpo, con unos 2 metros cuadrados en un adulto promedio.', 'Es un órgano que solemos ignorar.'],
    ['¿Cuál es el metal más abundante en la corteza terrestre?', ['Hierro', 'Calcio', 'Cobre', 'Aluminio'], 3, 'El aluminio es el metal más abundante en la corteza terrestre, aunque no se encuentra puro de forma natural.', 'Es tan común bajo tierra que supera con creces a los metales que más ves en el día a día.'],
    ['¿Qué país tiene el mayor consumo promedio de chocolate por habitante?', ['Bélgica', 'Alemania', 'Suiza', 'Austria'], 2, 'Suiza suele liderar el consumo de chocolate per cápita, con alrededor de 9-11 kg por persona al año, aunque algunos años Bélgica o Alemania pueden acercarse dependiendo de la fuente y el método de cálculo.', 'Es un país famoso por relojes, montañas… y chocolate.'],
    ['¿Qué animal puede vivir más tiempo?', ['Tortuga gigante de las Galápagos', 'Tiburón de Groenlandia', 'Cocodrilo del Nilo', 'Ballena azul'], 1, 'El tiburón de Groenlandia es el vertebrado más longevo conocido: puede superar los 300 años y algunos estudios estiman más de 400. Las tortugas gigantes de las Galápagos rondan los 150-200 años, los cocodrilos del Nilo unos 70-100 y la ballena azul unos 80-90.', 'Vive en aguas muy frías y envejece muy, muy despacio.'],
    ['¿Qué país tiene la mayor altitud media?', ['Nepal', 'Tíbet (China)', 'Bután', 'Perú'], 1, 'El Tíbet, una región autónoma de China, tiene la mayor altitud media del mundo, con aproximadamente 4.500 metros sobre el nivel del mar. Esto se debe a su ubicación en la meseta tibetana, rodeada por las montañas más altas del mundo.', 'La clave está en la meseta más alta del mundo.'],
    ['¿Cuál es la catarata más alta del mundo?', ['Niágara', 'Iguazú', 'Ángel', 'Victoria'], 2, 'El Salto Ángel, ubicado en Venezuela, es la catarata más alta del mundo con 979 metros de altura total, incluyendo una caída continua de 807 metros.', 'El nombre ya sugiere una caída enorme.'],
    ['¿Con cuántos países hace frontera España?', ['2', '3', '4', '5'], 3, 'España hace frontera con 5 países: Portugal, Francia, Andorra, Marruecos (en Ceuta y Melilla) y el Reino Unido (en Gibraltar). Es una de las fronteras más variadas de Europa por su mezcla de territorios continentales y enclaves.', 'Incluye un pequeño territorio británico y dos ciudades en África.'],
    ['¿Qué país tiene la mayor cantidad de islas del mundo?', ['Suecia', 'Filipinas', 'Indonesia', 'Canadá'], 0, 'Suecia tiene más de 200.000 islas, muchas de ellas deshabitadas. Es un dato sorprendente porque solemos asociar este récord a países tropicales como Indonesia.', 'No es tropical, pero tiene miles y miles de pequeñas islas.'],
    ['¿Cuál es el desierto más grande del mundo?', ['Antártida', 'Gobi', 'Sahara', 'Kalahari'], 0, 'Aunque no lo parezca, la Antártida es un desierto por su baja precipitación, y es el más grande del planeta. Se considera desierto porque recibe menos de 50 mm de precipitación anual en su interior, la definición se basa en la aridez, no en el calor.', 'Es un desierto, pero no es cálido.'],
    ['¿Qué país tiene dos capitales principales (constitucional y administrativa)?', ['Sudáfrica', 'Bolivia', 'Países Bajos', 'Benín'], 1, 'Bolivia tiene dos capitales principales: Sucre (capital constitucional) y La Paz (sede del gobierno). Otros países, como Sudáfrica, también cuentan con varias capitales con distintas funciones.', 'Una capital es histórica, la otra es donde se gobierna.'],
    ['¿Cuál de estos países NO tiene salida al mar?', ['Bolivia', 'Sudán', 'Camboya', 'Uruguay'], 0, 'Bolivia es un país sin salida al mar desde la Guerra del Pacífico. Sudán tiene costa en el Mar Rojo, Camboya en el Golfo de Tailandia y Uruguay en el Atlántico.', 'Perdió su salida al mar hace más de un siglo.'],
    ['¿Cuál es la capital más alta del mundo?', ['Quito (Ecuador)', 'La Paz (Bolivia)', 'Bogotá (Colombia)', 'Adís Abeba (Etiopía)'], 1, 'La Paz, sede del gobierno de Bolivia, se encuentra a unos 3.640 metros sobre el nivel del mar, lo que la convierte en la capital más alta del mundo. Quito está a 2.850 m, Bogotá a 2.640 m y Adís Abeba a 2.355 m.', 'Su país es conocido por tener el salar más grande del mundo.'],
  ]),
};
